swagger: "2.0"
info:
  title: Poker server API
  description: API игрового сервера Расписного покера
  version: 1.0.0
  contact:
    name: Balychkov Vyacheslav
    email: balychkov@bobday.ru
  license:
    name: n/a
host: localhost
basePath: /api/v1
schemes:
  - https
  - http
tags:
  - name: Auth
    description: Механизм авторизации
  - name: Users
    description: Работа с пользователем
  - name: Game
    description: Методы игрового процесса
paths:
  /register:
    post:
      tags:
        - Auth
      summary: Регистрация пользователя
      consumes:
        - 'application/json'
      operationId: 'register'
      parameters:
        - in: 'body'
          name: 'reg_data'
          description: 'Данные для регистрации'
          required: true
          schema:
            $ref: '#/definitions/RegUser'
      responses:
        200:
          description: 'OK'
          schema:
            $ref: '#/definitions/response_default'
        400:
          description: 'Неверно заполнены регистрационные данные'
          schema:
            $ref: '#/definitions/response_default'
  /auth:
    post:
      tags:
        - Auth
      summary: Авторизация
      consumes:
        - 'application/json'
      operationId: 'auth'
      parameters:
        - in: body
          name: 'auth_data'
          description: 'Данные для авторизации'
          required: true
          schema:
            $ref: '#/definitions/Auth'
      responses:
        200:
          description: "ОК"
          schema:
            type: object
            properties:
              session_key:
                type: string
                description: "Сеансовый ключ, который надо передавать в хедерах всех дальнейших запросов. Без него запрос считается не авторизованным"
        400:
          description: 'Ошибка авторизации'
          schema:
            $ref: '#/definitions/response_default'
definitions:
  response_default:
    type: 'object'
    properties:
      code:
        type: 'string'
      message:
        type: 'string'
  RegUser:
    type: object
    properties:
      login:
        type: string
      password:
        type: string
      name:
        type: string
      avatar:
        type: string
        x-nullable: true
      is_robot:
        type: boolean
        description: Робот / Человек
      ai_risk_level:
        type: integer
        x-nullable: true
        description: Уровень риска для игрока робота
      ai_skill:
        type: integer
        x-nullable: true
        description: Уровень сложности для игрока робота
  Auth:
    type: object
    properties:
      login:
        type: string
      password:
        type: string
  User:
    type: object
    properties:
      uid:
        type: string
      login:
        type: string
      name:
        type: string
      avatar:
        type: string
      is_robot:
        type: boolean
      ai_risk_level:
        type: integer
      ai_skill:
        type: integer
      total_money:
        type: number
        format: double
      owner_uid:
        type: string
        x-nullable: true
        description: Ссылка на создателя/владельца для игрока робота